name: voila
channels:
  - conda-forge
dependencies:
  - voila
  - ipywidgets
  - ipykernel
  - pip
  - matplotlib
  - scipy
  - pygtrie
  - varname
  - numpy
  - pillow
  
  - pip:
    - voila-topbar==0.1.1
